// =====================================================================
// HOME — the company as a node system. The route starts at the centre and
// branches outward in this order: Tiaki Mai Rā · What we do · Skills ·
// Who we are · What we make · How we work · Connect.
// Copy is drafted from the vault and UNVERIFIED FOR PUBLICATION.
// angle: degrees, 0 = right, 90 = down. r: distance from the parent node.
// =====================================================================
window.HOME = {
  name: 'Tiaki Mai Rā', headline: 'Bringing the old to the new, and the future to the past.',
  prelude: { line1: 'Everything we make flows to one place.', line2: 'Scroll to go inside.' },
  phases: [
    { id: 'core', name: 'Tiaki Mai Rā', colour: '#16130f', shape: 'circle', bg: 'flow' },
    { id: 'do', name: 'What we do', colour: '#1f7a5c', shape: 'square', bg: 'binary' },
    { id: 'who', name: 'Who we are', colour: '#6b3fa0', shape: 'diamond', bg: 'foam' },
    { id: 'skills', name: 'Technical skills', colour: '#0e6f8a', shape: 'hexagon', bg: 'hexes' },
    { id: 'make', name: 'What we make', colour: '#2a3d8f', shape: 'circle', bg: 'dots' },
    { id: 'how', name: 'How we work', colour: '#a5762a', shape: 'triangle', bg: 'contours' },
    { id: 'connect', name: 'Connect', colour: '#d9521b', shape: 'square', bg: 'circuit' },
  ],
  nodes: [
    { id: 'core', phase: 'core', kicker: 'Tiaki Mai Rā Limited', title: 'Bringing the old to the new, and the future to the past.', body: ['A New Zealand digital product studio. We design and build products, from the first sketch to the deploy, across web, mobile, AR and spatial computing, with AI inside and cultural grounding at the centre of the work.', 'Everything branches from here. Follow the line, or pick a node.'], size: 34 },

    // ---- 1. What we do
    { id: 'do', parent: 'core', angle: 195, r: 900, phase: 'do', kicker: 'What we do', title: 'Digital product development, end to end.', body: ['We take a product from problem to shipped: research and strategy, UI and UX design, full-stack build, AI integration, immersive AR/VR/XR, testing and release. One small team that can carry the whole lifecycle, or slot into yours.', 'The problem we solve: organisations, cultural groups and small businesses need AI and new interfaces, cannot afford full teams, and are offered technology built without cultural grounding or care for the people who use it.', 'Who it is for: organisations adopting AI and immersive tools; construction and training providers; iwi, marae and cultural organisations; education; small businesses; and the people who use what we build.'], size: 22 },
    { id: 'do-ux', parent: 'do', angle: 140, r: 470, phase: 'do', kicker: 'Service', title: 'UI and UX design', body: ['User research, journeys, wireframes, design systems, prototypes, accessibility and cultural review. Every decision recorded, so the design can be explained, not just shown.'], size: 12 },
    { id: 'do-build', parent: 'do', angle: 180, r: 490, phase: 'do', kicker: 'Service', title: 'Product build', body: ['Web apps and PWAs, iOS apps, marketplaces, dashboards and admin tools. Supabase, Next.js, React, Swift. Shipped on real infrastructure with real tests.'], size: 12 },
    { id: 'do-ai', parent: 'do', angle: 218, r: 480, phase: 'do', kicker: 'Service', title: 'AI assistants and automations', body: ['Agentic assistants, knowledge bases, workflow automation and routing. Built so the system saves what it says it saves, and so a bad actor cannot run up your bill.'], size: 12 },
    { id: 'do-xr', parent: 'do', angle: 256, r: 470, phase: 'do', kicker: 'Service', title: 'Immersive AR / VR / XR', body: ['Apple Vision Pro, iOS AR, HoloLens. Spatial storytelling and training that happens where the stories, the hazards and the people are.'], size: 12 },
    { id: 'do-dx', parent: 'do', angle: 294, r: 460, phase: 'do', kicker: 'Service', title: 'Digital transformation and adoption', body: ['Discovery, strategy, adoption and delivery for teams that need it end to end, and need it to stick after we leave.'], size: 12 },
    { id: 'do-story', parent: 'do', angle: 330, r: 470, phase: 'do', kicker: 'Service', title: 'Cultural storytelling', body: ['Immersive narrative work with cultural organisations, with permissions and authority respected at every step.'], size: 12 },

    // ---- 2. Who we are
    { id: 'who', parent: 'core', angle: 252, r: 960, phase: 'who', kicker: 'Who we are', title: 'Founded by two people. Each project has its own contributors.', body: ['Both founders trained at AUT in Creative Technologies. The people around each project are named per project.'], size: 22 },
    { id: 'thomas', parent: 'who', angle: 270, r: 500, phase: 'who', kicker: 'Co-founder', title: 'Thomas Kereama Perese', body: ['Creative technologist: AR/VR, Apple Vision Pro, full-stack development, product, Indigenous design.', 'Master of Philosophy in Creative Technologies, AUT (2025), First-Class Honours, fully funded by a competitive scholarship. Thesis: Guardians of Matariki, a spatial storytelling prototype for mixed reality on the Apple Vision Pro.', 'Bachelor of Creative Technologies, AUT (2021–2023): top student of the year in all three years, Dean\'s Award, seven academic awards and five scholarships.'], photo: 'assets/thomas-perese.jpg', links: [{ label: 'LinkedIn', href: 'https://www.linkedin.com/in/thomas-perese-140441190' }], size: 13 },
    { id: 'ray', parent: 'who', angle: 318, r: 520, phase: 'who', kicker: 'Co-founder', title: 'Ray Jonson Tui Hikaka', body: ['Creative technologist and researcher: research and development, data analysis, product development, immersive technologies, and artificial intelligence through a Polynesian lens, with the methodologies and frameworks to carry a project from question to product.', 'Bachelor of Creative Technologies, Master of Creative Technologies and PhD in Creative Technologies, AUT. Master\'s thesis: Enhancing Construction Health and Safety Training using Handheld Augmented Reality for Site Safety Protocols in New Zealand (2025), the research behind KINsafe.', 'Partner in Tiaki Mai Rā Limited; co-founder of KINsafe; collaborator on Guardians of Matariki and Nearby Stock.'], photo: 'assets/ray-hikaka.jpg', links: [{ label: 'LinkedIn', href: 'https://www.linkedin.com/in/ray-jonson-tui-hikaka-5973a1213/' }, { label: 'Master\'s thesis (AUT)', href: 'https://openrepository.aut.ac.nz/items/9b95c831-acfa-45e7-8a8c-65c8f5db9519' }], size: 13 },
    { id: 'contrib', parent: 'who', angle: 6, r: 520, phase: 'who', kicker: 'Project contributors', title: 'The people around the projects', body: ['Every project is a group effort. These are the people who shaped them, by project.'], items: ['Otene Hopa · cultural lead, KINsafe', 'Donna Perese · stakeholder and industry relationships, KINsafe; community and market validation, Nearby Stock', 'Ray Hikaka · KINsafe, Guardians of Matariki, Nearby Stock', 'Professor Rachel Shearer · primary supervisor, Guardians of Matariki (AUT)', 'Professor Stefan Marks · secondary supervisor, Guardians of Matariki (AUT)', 'Dr Zena Elliott · artist, Guardians of Matariki artwork (Ngāti Awa)', 'Piripi Taylor · cultural advisor and voice, Guardians of Matariki'], size: 12 },
    { id: 'partners', parent: 'who', angle: 50, r: 500, phase: 'who', kicker: 'Partners and stakeholders', title: 'Organisations in the work', body: ['Organisations we have worked with or alongside. Listing is not endorsement.'], items: ['Auckland University of Technology · research home', 'WorkSafe New Zealand · regulator in conversation, KINsafe', 'Toi Ohomai · AR storytelling', 'TINA · digital transformation for small business', 'Māori non-profits · cultural storytelling', 'Past: SkillsVR, 3C Codes, Accenture'], size: 11 },

    // ---- 3. Technical skills (knowledge blocks from the founders' records)
    { id: 'skills', parent: 'core', angle: 312, r: 980, phase: 'skills', kicker: 'Skills', title: 'The technical range behind the work.', body: ['Grouped into knowledge blocks. Each block lists what we actually use, not what we have heard of. Ray\'s blocks will be added from his record.'], size: 22 },
    { id: 'sk-prog', parent: 'skills', angle: 200, r: 500, phase: 'skills', kicker: 'Programming', title: 'Languages and frameworks', items: ['Swift', 'SwiftUI', 'RealityKit', 'ARKit', 'TypeScript', 'JavaScript', 'React', 'Next.js', 'Node.js', 'Express', 'HTML', 'CSS', 'C#', 'Java', 'Python', 'SQL', 'PostgreSQL', 'MongoDB', 'Supabase', 'REST APIs', 'object-oriented design', 'SOLID'], size: 12 },
    { id: 'sk-xr', parent: 'skills', angle: 232, r: 520, phase: 'skills', kicker: 'AR / VR / spatial', title: 'Immersive platforms', items: ['Apple Vision Pro / visionOS', 'ARKit', 'ARCore', 'AR Foundation', 'HoloLens 2 / MRTK', 'Reality Composer Pro', 'Unity', 'Unreal Engine', 'Snap Lens', 'Gaussian splats', 'USDZ pipeline', 'hand and gaze input'], size: 12 },
    { id: 'sk-3d', parent: 'skills', angle: 264, r: 520, phase: 'skills', kicker: '3D modelling and animation', title: '3D, rigging, motion', items: ['Blender', 'Maya', 'Rhino', 'Fusion 360', 'Spline 3D', 'Meshy AI', 'Mixamo', 'rigging and shape keys', 'USD / USDZ export', 'animation clips to RealityKit', 'procedural assets'], size: 12 },
    { id: 'sk-design', parent: 'skills', angle: 296, r: 520, phase: 'skills', kicker: 'Design', title: 'UI / UX and visual', items: ['Figma', 'Adobe Illustrator', 'After Effects', 'Premiere Pro', 'Webflow', 'design systems', 'wireframes and storyboards', 'accessibility (WCAG)', 'motion design', 'Apple HIG', 'user-centred design', 'Double Diamond'], size: 12 },
    { id: 'sk-ai', parent: 'skills', angle: 328, r: 500, phase: 'skills', kicker: 'AI and automation', title: 'Agentic systems', items: ['Claude and Claude Code', 'Gemini', 'ChatGPT', 'prompt and schema design', 'structured-output validation', 'routers and specialists', 'knowledge bases', 'rate limiting and abuse hardening', 'MCP tools', 'AI-assisted 3D and asset pipelines'], size: 12 },
    { id: 'sk-hw', parent: 'skills', angle: 168, r: 460, phase: 'skills', kicker: 'Physical computing', title: 'Mechatronics and electronics', items: ['Arduino', 'RFID', 'sensors', 'LCD displays', 'Wi-Fi modules', 'circuit design', 'embedded prototypes'], size: 11 },
    { id: 'sk-biz', parent: 'skills', angle: 360, r: 480, phase: 'skills', kicker: 'Entrepreneurship', title: 'Building the business', items: ['company formation', 'pricing and unit economics', 'pilots and partnerships', 'programme applications', 'pitching and presenting', 'legal and privacy drafting', 'Stripe and App Store billing', 'operations and bookkeeping'], size: 11 },
    { id: 'sk-ops', parent: 'skills', angle: 136, r: 460, phase: 'skills', kicker: 'Delivery and platforms', title: 'How it ships', items: ['Git and GitHub', 'Netlify', 'Supabase', 'Xcode and TestFlight', 'App Store', 'Cloudinary', 'Playwright and Vitest', 'Jira, Trello, Monday', 'Agile / Scrum', 'decision records'], size: 11 },

    // ---- 4. What we make
    { id: 'make', parent: 'core', angle: 10, r: 1000, phase: 'make', kicker: 'What we make', title: 'Every project is a node. Choose one to travel its roadmap.', body: ['Products, research and founder experience are kept distinct. Each project page is a journey: every design decision from ideation to now, told as it happened.'], size: 22 },
    { id: 'gom', parent: 'make', angle: -70, r: 520, phase: 'make', kicker: 'Research prototype · visionOS', title: 'Guardians of Matariki', body: ['A spatial storytelling experience for Apple Vision Pro, grounded in Matariki. Sprint 03 build-out, pre-release, no external study yet.'], journey: 'gom', accent: '#2a3d8f', shape: 'circle', size: 14 },
    { id: 'kinsafe', parent: 'make', angle: -28, r: 540, phase: 'make', kicker: 'Product · iOS AR', title: 'KINsafe', body: ['AR safety training that turns a learner\'s own space into a construction scenario. TestFlight target.'], journey: 'kinsafe', accent: '#d9521b', shape: 'triangle', size: 14 },
    { id: 'tiaki', parent: 'make', angle: 12, r: 540, phase: 'make', kicker: 'Product · web PWA', title: 'Tiaki', body: ['An AI assistant that carries your context so you never pay the restart tax. Live prototype.'], journey: 'tiaki', accent: '#1f7a5c', shape: 'square', size: 14 },
    { id: 'nearby', parent: 'make', angle: 52, r: 540, phase: 'make', kicker: 'Product · Next.js PWA', title: 'Nearby Stock', body: ['Wholesale stock near you, when you need it. MVP complete in demo mode.'], journey: 'nearby', accent: '#a5762a', shape: 'hexagon', size: 14 },
    { id: 'waga', parent: 'make', angle: 92, r: 520, phase: 'make', kicker: 'Experimental · visionOS', title: 'WAGA · World Art Generator', body: ['Generate and walk into spatial worlds on Apple Vision Pro. On-device build, persistence verified.'], journey: 'waga', accent: '#6b3fa0', shape: 'diamond', size: 14 },
    { id: 'exp', parent: 'make', angle: 136, r: 560, phase: 'make', kicker: 'Founder experience · not company products', title: 'Past works, roles and prototypes', body: ['Links go to the current public pages and videos.'], links: [
        { label: 'My Story', href: 'https://tiakimaira.com/my-story/' }, { label: 'Microsoft HoloLens', href: 'https://youtu.be/ezRUdjYpfCM' }, { label: 'HoloLens 2 MRTK', href: 'https://youtu.be/n2o9SX4FM3c' },
        { label: 'SkillsVR training modules', href: 'https://www.linkedin.com/posts/thomas-perese-140441190_mentalwellness-immersivetechnology-vrtraining-activity-6981319841764827136-eb1U' }, { label: 'Indigenous AR concepts', href: 'https://youtu.be/cHgGJdDxML8' }, { label: 'Smart Stop', href: 'https://youtu.be/CEmShMY31d4' }, { label: 'Earlier Tiaki chatbot', href: 'https://youtu.be/OfG2aAhmLfo' },
      ], items: ['Accenture Song · internship, no public link', 'Spatial Invaders · visionOS prototype', 'Blender character pipeline · rigging to USDZ to visionOS'], size: 12 },

    // ---- 5. How we work
    { id: 'how', parent: 'core', angle: 68, r: 900, phase: 'how', kicker: 'How we work', title: 'Discover, define, develop, deliver. Evidence before assumptions.', body: ['A Double Diamond spine with research methods inside it, agile delivery around it, and a written decision record at every turn. Every project journey on this site is this process, shown rather than described.', 'Three commitments: cultural authority is named before cultural work starts; a design is locked before code depends on it; nothing is claimed that the evidence does not support.'], size: 22 },
    { id: 'how-1', parent: 'how', angle: 10, r: 500, phase: 'how', kicker: '1 · Discover', title: 'Find out what is true before deciding what to build.', body: ['Research framing with the Research Onion; Kaupapa Māori and Design-Based Research where they fit; personas built from real contexts; domain briefs; reflective journals; heuristic walkthroughs of what exists.'], items: ['Research Onion', 'Design-Based Research', 'Kaupapa Māori', 'personas', 'domain briefs', 'heuristic review'], size: 11 },
    { id: 'how-2', parent: 'how', angle: 48, r: 520, phase: 'how', kicker: '2 · Define', title: 'Lock the design before code depends on it.', body: ['Journeys and storyboards; a backlog prioritised with MoSCoW; user stories; design-system and motion contracts; cultural-review holds cleared in structured sittings; a dated decision record for every call.'], items: ['Double Diamond', 'MoSCoW', 'user stories', 'storyboards', 'design contracts', 'decision records'], size: 11 },
    { id: 'how-3', parent: 'how', angle: 88, r: 520, phase: 'how', kicker: '3 · Develop', title: 'Small, reversible steps on the real device.', body: ['Agile sprints with reviews and retrospectives; one design-agnostic plumbing ticket before feature work; clone-and-swap patterns for repeated content; SOLID, DRY, KISS and YAGNI as the code rules; the owner on the headset or phone every round.'], items: ['Agile / Scrum', 'sprints and retros', 'SOLID · DRY · KISS · YAGNI', 'on-device rounds', 'asset pipelines'], size: 11 },
    { id: 'how-4', parent: 'how', angle: 126, r: 500, phase: 'how', kicker: '4 · Deliver', title: 'Nothing ships past a gate it has not earned.', body: ['Functional, accessibility, performance and security checks; NASA-TLX and TAM-informed evaluation when it fits; cultural review before any public showing; honest limitations recorded next to results; release notes and rollback.'], items: ['NASA-TLX', 'TAM', 'cultural review checklist', 'security review', 'reduced-motion paths', 'release and rollback'], size: 11 },
    { id: 'how-5', parent: 'how', angle: 160, r: 470, phase: 'how', kicker: 'Thinking tools', title: 'For when the answer is not obvious.', body: ['Lotus Blossom to open a problem up; Six Thinking Hats to argue with ourselves; Cognitive Load Theory and Bloom\'s taxonomy when something has to teach; STAR to explain what we did and what came of it.'], items: ['Lotus Blossom', 'Six Thinking Hats', 'Cognitive Load Theory', 'Bloom\'s taxonomy', 'STAR'], size: 11 },
    { id: 'how-6', parent: 'how', angle: 200, r: 460, phase: 'how', kicker: 'With AI', title: 'AI in the loop, people on the decisions.', body: ['We run specialist AI agents under a project manager pattern, with a vault of context per project and a written handoff between every stage. The owner approves scope, culture and release; the agents do the legwork and record it.'], items: ['project vaults', 'specialist agents', 'handoff briefs', 'owner approvals'], size: 11 },

    // ---- 6. Connect
    { id: 'connect', parent: 'core', angle: 118, r: 1400, phase: 'connect', kicker: 'Connect', title: 'Tell us about your project.', body: ['Email: peresethomas649@gmail.com'], form: true, size: 22 },
    { id: 'social', parent: 'connect', angle: 20, r: 460, phase: 'connect', kicker: 'Find us', title: 'Social', body: ['Where we are online today. More channels as they open.'], links: [{ label: 'Thomas on LinkedIn', href: 'https://www.linkedin.com/in/thomas-perese-140441190' }, { label: 'Ray on LinkedIn', href: 'https://www.linkedin.com/in/ray-jonson-tui-hikaka-5973a1213/' }, { label: 'GitHub', href: 'https://github.com/peresethomas649-byte' }], size: 11 },
    { id: 'legal', parent: 'connect', angle: 160, r: 460, phase: 'connect', kicker: 'Legal', title: 'Terms and privacy, always reachable.', body: ['Plain language, no motion. This is the end of the route: keep scrolling to see the whole network and return to the start.'], links: [{ label: 'Terms of Use', href: 'legal.html#terms' }, { label: 'Privacy Statement', href: 'legal.html#privacy' }], size: 11 },
  ],
};
