/* Compiled from guardians.source.jsx. Do not edit this file directly unless you are doing a quick static-site patch. */
// ─────────────────────────────────────────────────────────────
// CONFIG
// ─────────────────────────────────────────────────────────────
const CONFIG = {
    hero: {
        eyebrow: "VISIONOS · SPATIAL STORYTELLING · 2026",
        title: "Guardians of",
        titleEm: "Matariki",
        subtitle: "A spatial storytelling experience for Apple Vision Pro exploring Matariki, Māori cultural narrative, and immersive learning.",
        byline: "Designed and developed by Thomas Kereama Perese",
        youtubeId: "wJCQBSAyWDU",
        ctas: [
            { label: "View Project", href: "#headset", primary: true },
            { label: "Watch Demo", href: "#demo" },
            { label: "Read Research", href: "https://openrepository.aut.ac.nz/items/68b37076-8eab-45a1-bd65-c9f4f5721e3b" },
        ],
    },
    headset: {
        eyebrow: "SECTION 02 · ARCHITECTURE",
        title: "One narrative, woven across three spatial layers.",
        callouts: [
            { num: "01", label: "Windowed Interface", desc: "2D SwiftUI · navigation", x: -38, y: -22 },
            { num: "02", label: "Volumetric Scene", desc: "3D content in your space", x: 36, y: -28 },
            { num: "03", label: "Immersive Space", desc: "Full environmental shift", x: -42, y: 18 },
            { num: "04", label: "Spatial Audio", desc: "Directional storytelling", x: 40, y: 20 },
            { num: "05", label: "Gesture Interaction", desc: "Hand · gaze · pinch", x: -28, y: 34 },
            { num: "06", label: "Matariki Narrative", desc: "Cultural learning pathway", x: 30, y: 38 },
        ],
    },
    stars: [
        { id: "matariki", name: "Matariki", domain: "Reflection · Wellbeing", x: 50, y: 38, big: true,
            desc: "The eyes of the chief; the sign of the new year. Matariki signals a time of remembrance, reflection, and gathering." },
        { id: "pohutukawa", name: "Pōhutukawa", domain: "Those who have passed", x: 38, y: 28,
            desc: "Carries the memory of those who have passed in the year, lifting them into the night sky." },
        { id: "tupuanuku", name: "Tupuānuku", domain: "Food from the soil", x: 32, y: 50,
            desc: "Connected to food gathered and grown in the earth — kūmara, vegetables, the harvest of the land." },
        { id: "tupuarangi", name: "Tupuārangi", domain: "Food from above", x: 60, y: 30,
            desc: "Associated with food gathered from above — birds and the elevated forest fruits." },
        { id: "waiti", name: "Waitī", domain: "Fresh water", x: 42, y: 58,
            desc: "Watches over freshwater — rivers, lakes, streams, and the food sources within them." },
        { id: "waita", name: "Waitā", domain: "Salt water", x: 64, y: 52,
            desc: "Connected to the ocean and the food drawn from the salt waters that surround Aotearoa." },
        { id: "waipunarangi", name: "Waipunarangi", domain: "Rain", x: 48, y: 22,
            desc: "Associated with rain that gathers in the sky and falls to nourish the land." },
        { id: "ururangi", name: "Ururangi", domain: "Winds", x: 70, y: 40,
            desc: "Connected to the winds — the breath that moves across earth and sea." },
        { id: "hiwa", name: "Hiwa-i-te-rangi", domain: "Hopes & aspirations", x: 56, y: 64,
            desc: "The youngest star, where wishes and aspirations for the year ahead are sent." },
    ],
    experiences: [
        {
            index: "01 — 2D",
            title: "Windowed Experience",
            desc: "A SwiftUI interface introduces the story, navigation, and learning pathway — a calm entry point into the world of Matariki.",
            note: "Touch · Gaze",
            v: "v1",
            label: "WINDOW · 2D INTERFACE",
        },
        {
            index: "02 — 3D",
            title: "Volumetric Experience",
            desc: "Matariki characters and elements exist within your physical space, bridging the real world and the cultural narrative.",
            note: "Pinch · Move · Inspect",
            v: "v2",
            label: "VOLUME · 3D OBJECTS",
        },
        {
            index: "03 — XR",
            title: "Fully Immersive Experience",
            desc: "A spatial environment surrounds you. The Matariki story unfolds through atmosphere, sound, presence, and movement.",
            note: "Walk · Listen · Witness",
            v: "v3",
            label: "SPACE · IMMERSIVE",
        },
    ],
    values: [
        { key: "Manaakitanga", en: "Care · Hospitality", desc: "The wellbeing of the visitor is held with care. The experience welcomes, never imposes." },
        { key: "Kaitiakitanga", en: "Guardianship", desc: "Story, knowledge, and place are treated as taonga to be protected — not consumed." },
        { key: "Whakawhanaungatanga", en: "Building relationships", desc: "Relationship between user, story, and tūpuna is built slowly — through presence, not performance." },
    ],
    creator: {
        name: "Thomas Kereama Perese",
        role: "Creative Technologist · Aotearoa",
        bio: "Māori / Pacific creative technologist working across spatial computing, immersive storytelling, AI, and culturally grounded design. Guardians of Matariki was developed as a research prototype exploring how spatial computing can serve cultural narrative.",
        initials: "TP",
    },
    links: {
        demo: "#demo",
        research: "https://openrepository.aut.ac.nz/items/68b37076-8eab-45a1-bd65-c9f4f5721e3b",
        portfolio: "https://tiakimaira.com/",
        contact: "mailto:hello@example.com",
    },
};
// ─────────────────────────────────────────────────────────────
// TWEAKS PANEL
// ─────────────────────────────────────────────────────────────
function useTweaks(defaults) {
    const [values, setValues] = React.useState(defaults);
    const setTweak = React.useCallback((keyOrEdits, val) => {
        const edits = typeof keyOrEdits === 'object' && keyOrEdits !== null
            ? keyOrEdits : { [keyOrEdits]: val };
        setValues((prev) => ({ ...prev, ...edits }));
        window.parent.postMessage({ type: '__edit_mode_set_keys', edits }, '*');
    }, []);
    return [values, setTweak];
}
// ─────────────────────────────────────────────────────────────
// HOOKS + TWEAK DEFAULTS
// ─────────────────────────────────────────────────────────────
const { useState, useEffect, useRef, useMemo, useCallback } = React;
const TWEAK_DEFAULTS = /*EDITMODE-BEGIN*/ {
    "accent": "#7cc9ff",
    "warmAccent": "#ffd9a8",
    "starGlow": 1.0,
    "blur": 22,
    "explodeDistance": 1.0,
    "scrollIntensity": 1.0,
    "starsXOffset": 0,
    "starsYOffset": 0,
    "starsScale": 1.0
} /*EDITMODE-END*/;
function useSectionProgress(ref) {
    const [p, setP] = useState(0);
    useEffect(() => {
        let raf = 0;
        const tick = () => {
            const el = ref.current;
            if (!el)
                return;
            const rect = el.getBoundingClientRect();
            const total = rect.height - window.innerHeight;
            const scrolled = -rect.top;
            const prog = Math.max(0, Math.min(1, scrolled / Math.max(1, total)));
            setP(prog);
        };
        const onScroll = () => { cancelAnimationFrame(raf); raf = requestAnimationFrame(tick); };
        onScroll();
        window.addEventListener('scroll', onScroll, { passive: true });
        window.addEventListener('resize', onScroll);
        return () => {
            window.removeEventListener('scroll', onScroll);
            window.removeEventListener('resize', onScroll);
            cancelAnimationFrame(raf);
        };
    }, [ref]);
    return p;
}
function useReveal() {
    useEffect(() => {
        const els = document.querySelectorAll('.reveal');
        const io = new IntersectionObserver((entries) => {
            entries.forEach((e) => {
                if (e.isIntersecting)
                    e.target.classList.add('on');
            });
        }, { threshold: 0.15 });
        els.forEach((el) => io.observe(el));
        return () => io.disconnect();
    }, []);
}
function useScrollY() {
    const [y, setY] = useState(0);
    useEffect(() => {
        const onScroll = () => setY(window.scrollY);
        window.addEventListener('scroll', onScroll, { passive: true });
        return () => window.removeEventListener('scroll', onScroll);
    }, []);
    return y;
}
// ─────────────────────────────────────────────────────────────
// HERO
// ─────────────────────────────────────────────────────────────
function DemoVideo({ id }) {
    const [playing, setPlaying] = useState(false);
    const src = `https://www.youtube.com/embed/${id}?autoplay=1&rel=0&modestbranding=1&playsinline=1`;
    const thumb = `https://i.ytimg.com/vi/${id}/maxresdefault.jpg`;
    return (React.createElement("div", { className: "demo-video glass" },
        React.createElement("div", { className: "demo-chrome" },
            React.createElement("span", { className: "dot r" }),
            React.createElement("span", { className: "dot y" }),
            React.createElement("span", { className: "dot g" }),
            React.createElement("span", { className: "demo-title" }, "Guardians of Matariki \u2014 Demo"),
            React.createElement("span", { className: "demo-meta" }, "visionOS \u00B7 1080p")),
        React.createElement("div", { className: "demo-frame" }, playing ? (React.createElement("iframe", { src: src, title: "Guardians of Matariki \u2014 Demo", allow: "accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture", allowFullScreen: true, frameBorder: "0" })) : (React.createElement("button", { className: "demo-poster", onClick: () => setPlaying(true), "aria-label": "Play demo" },
            React.createElement("img", { src: thumb, alt: "", onError: (e) => { e.currentTarget.style.display = 'none'; } }),
            React.createElement("span", { className: "demo-poster-overlay" }),
            React.createElement("span", { className: "demo-play" },
                React.createElement("svg", { width: "22", height: "22", viewBox: "0 0 22 22", fill: "none" },
                    React.createElement("path", { d: "M6 4 L18 11 L6 18 Z", fill: "#fff" }))),
            React.createElement("span", { className: "demo-poster-label" }, "Play demo"))))));
}
function Headset({ scale = 1, style = {} }) {
    return (React.createElement("div", { className: "headset", style: { transform: `scale(${scale})`, ...style } },
        React.createElement("div", { className: "band" }),
        React.createElement("div", { className: "frame" }),
        React.createElement("div", { className: "visor" },
            React.createElement("div", { className: "highlight" }))));
}
function Hero({ tweak }) {
    const scrollY = useScrollY();
    const intensity = tweak.scrollIntensity;
    const heroProg = Math.min(1, scrollY / (typeof window !== 'undefined' ? window.innerHeight : 1));
    const titleStyle = {
        transform: `translateY(${-heroProg * 80 * intensity}px)`,
        opacity: 1 - heroProg * 0.9,
    };
    const deviceStyle = {
        transform: `translateY(${-heroProg * 30 * intensity}px) scale(${1 + heroProg * 0.18 * intensity}) rotateX(${heroProg * 8}deg)`,
        opacity: 1 - heroProg * 0.6,
    };
    const glowStyle = {
        transform: `translate(-50%,-50%) scale(${1 + heroProg * 0.5})`,
        opacity: 0.9 - heroProg * 0.5,
    };
    return (React.createElement("section", { className: "hero", id: "hero" },
        React.createElement("div", { style: titleStyle },
            React.createElement("div", { className: "eyebrow" }, CONFIG.hero.eyebrow),
            React.createElement("h1", { style: { marginTop: 18 } },
                CONFIG.hero.title,
                " ",
                React.createElement("em", null, CONFIG.hero.titleEm)),
            React.createElement("p", { className: "subtitle" }, CONFIG.hero.subtitle),
            React.createElement("div", { className: "byline" }, CONFIG.hero.byline),
            React.createElement("div", { className: "ctas" }, CONFIG.hero.ctas.map((c, i) => (React.createElement("a", { key: i, className: "btn " + (c.primary ? "btn-primary" : ""), href: c.href },
                c.label,
                " ",
                React.createElement("span", { className: "arrow" }, "\u2192")))))),
        React.createElement("div", { id: "demo", className: "hero-video-wrap", style: deviceStyle },
            React.createElement("div", { className: "device-glow", style: glowStyle }),
            React.createElement(DemoVideo, { id: CONFIG.hero.youtubeId }))));
}
// ─────────────────────────────────────────────────────────────
// HEADSET SECTION
// ─────────────────────────────────────────────────────────────
const HEADSET_VIDEO = "https://res.cloudinary.com/dsqhj32yo/video/upload/q_auto/f_auto/v1778165428/Apple_Vision_Pro_Animation_Black_bmfojk.mp4";
function HeadsetSection({ tweak }) {
    const ref = useRef(null);
    const videoRef = useRef(null);
    const p = useSectionProgress(ref);
    const explode = tweak.explodeDistance;
    // Keep the video permanently paused so we can drive currentTime manually.
    // Also call v.load() explicitly — iOS Safari ignores preload="metadata" on
    // metered connections until user interaction, so without this v.duration
    // stays NaN and the RAF loop never seeks.
    useEffect(() => {
        const v = videoRef.current;
        if (!v)
            return;
        const keepPaused = () => v.pause();
        v.addEventListener('play', keepPaused);
        v.load(); // force iOS to start buffering immediately
        v.pause();
        return () => v.removeEventListener('play', keepPaused);
    }, []);
    // RAF loop: reads scroll every frame and lerps currentTime for smooth scrubbing.
    // Bypasses React's update batching so we get a seek attempt every ~16 ms.
    useEffect(() => {
        const v = videoRef.current;
        const section = ref.current;
        if (!v || !section)
            return;
        let raf;
        let lastTarget = -1;
        const tick = () => {
            const rect = section.getBoundingClientRect();
            const total = Math.max(1, rect.height - window.innerHeight);
            const prog = Math.max(0, Math.min(1, -rect.top / total));
            const dur = v.duration;
            if (dur && !isNaN(dur)) {
                const target = prog * Math.max(0, dur - 0.05);
                if (Math.abs(target - lastTarget) > 0.008) {
                    v.currentTime = target;
                    lastTarget = target;
                }
            }
            raf = requestAnimationFrame(tick);
        };
        raf = requestAnimationFrame(tick);
        return () => cancelAnimationFrame(raf);
    }, []);
    let ex = 0;
    if (p < 0.45)
        ex = p / 0.45;
    else if (p < 0.7)
        ex = 1;
    else
        ex = 1 - (p - 0.7) / 0.3;
    ex = Math.max(0, Math.min(1, ex));
    return (React.createElement("section", { className: "headset-section", id: "headset", ref: ref },
        React.createElement("div", { className: "headset-sticky" },
            React.createElement("video", { ref: videoRef, src: HEADSET_VIDEO, muted: true, playsInline: true, preload: "metadata", style: {
                    position: 'absolute', inset: 0,
                    width: '100%', height: '100%',
                    objectFit: 'contain',
                    background: '#000',
                    zIndex: 0,
                } }),
            React.createElement("div", { style: {
                    position: 'absolute', inset: 0, pointerEvents: 'none', zIndex: 1,
                    background: `radial-gradient(ellipse 60% 50% at 50% 50%, ${tweak.accent}1f, transparent 70%)`,
                    mixBlendMode: 'screen',
                } }),
            React.createElement("div", { className: "headset-eyebrow reveal", style: { zIndex: 3 } },
                React.createElement("div", { className: "eyebrow" }, CONFIG.headset.eyebrow),
                React.createElement("h2", null, CONFIG.headset.title)),
            React.createElement("div", { className: "headset-stage", style: { zIndex: 2, pointerEvents: 'none' } }, CONFIG.headset.callouts.map((c, i) => {
                const localOn = p > (0.32 + i * 0.02) && p < 0.78;
                const dx = c.x * (0.6 + ex * 0.8) * explode;
                const dy = c.y * (0.6 + ex * 0.8) * explode;
                // Scale offsets down on smaller viewports so callouts stay on-screen
                const vScale = Math.min(1, window.innerWidth / 960);
                return (React.createElement("div", { key: i, className: "callout " + (localOn ? "on" : "") + (i === 2 || i === 3 ? " callout-mid" : ""), style: {
                        left: `calc(50% + ${dx * 4 * vScale}px)`,
                        top: `calc(50% + ${dy * 4 * vScale}px)`,
                        transform: `translate(-50%, -50%) ${localOn ? '' : 'translateY(6px)'}`,
                    } },
                    React.createElement("span", { className: "num" },
                        c.num,
                        " \u00B7 ",
                        c.label.toUpperCase()),
                    c.desc));
            })),
            React.createElement("div", { className: "scrub-progress", style: { zIndex: 3 } },
                React.createElement("span", null, "SCROLL TO REVEAL"),
                React.createElement("div", { className: "bar" },
                    React.createElement("i", { style: { width: (p * 100).toFixed(1) + '%' } })),
                React.createElement("span", { style: { minWidth: 30 } },
                    Math.round(p * 100).toString().padStart(2, '0'),
                    "%")))));
}
// ─────────────────────────────────────────────────────────────
// STARS SECTION
// ─────────────────────────────────────────────────────────────
function StarsSection({ tweak }) {
    const ref = useRef(null);
    const p = useSectionProgress(ref);
    const [hover, setHover] = useState(null);
    const [active, setActive] = useState(null);
    const [hoverPos, setHoverPos] = useState({ x: 0, y: 0 });
    const conv = Math.min(1, p / 0.5);
    const settled = p > 0.45;
    const scattered = useMemo(() => {
        return CONFIG.stars.map((s, i) => {
            const seed = (i * 137) % 100;
            const sx = (seed * 9301 + 49297) % 100;
            const sy = (seed * 7919 + 12347) % 100;
            return { x: sx, y: sy };
        });
    }, []);
    const stage = useRef(null);
    const onLeave = () => setHover(null);
    return (React.createElement("section", { className: "stars-section", id: "stars", ref: ref },
        React.createElement("div", { className: "stars-sticky" },
            React.createElement("div", { className: "stars-eyebrow reveal" },
                React.createElement("div", { className: "eyebrow" }, "SECTION 03 \u00B7 STAR CLUSTER"),
                React.createElement("h2", null, "The cluster, in formation."),
                React.createElement("p", null, settled ? "Hover a star to read its name. Click to open its meaning." : "Scroll — the stars find their formation.")),
            React.createElement("div", { className: "stars-canvas", ref: stage, onMouseLeave: onLeave, style: {
                    transform: `translate(${tweak.starsXOffset}px, ${tweak.starsYOffset}px) scale(${tweak.starsScale})`,
                } },
                React.createElement("div", { style: {
                        position: 'absolute', left: '50%', top: '50%', transform: 'translate(-50%,-50%)',
                        width: '70%', height: '70%',
                        background: `radial-gradient(ellipse, ${tweak.accent}1a, transparent 70%)`,
                        filter: 'blur(40px)', opacity: 0.4 + conv * 0.6,
                        pointerEvents: 'none',
                    } }),
                CONFIG.stars.map((s, i) => {
                    const sx = scattered[i].x;
                    const sy = scattered[i].y;
                    const t = 1 - Math.pow(1 - conv, 3);
                    const x = sx + (s.x - sx) * t;
                    const y = sy + (s.y - sy) * t;
                    const size = s.big ? 22 : 14;
                    const isActive = active === s.id;
                    const glowMul = tweak.starGlow;
                    return (React.createElement("div", { key: s.id, className: "star " + (s.big ? "matariki " : "") + (settled ? "formed " : "") + (isActive ? "active " : ""), style: {
                            left: x + '%',
                            top: y + '%',
                            width: size, height: size,
                            filter: `drop-shadow(0 0 ${10 * glowMul}px ${s.big ? tweak.warmAccent : tweak.accent})`,
                        }, onMouseEnter: (e) => {
                            if (!settled)
                                return;
                            setHover(s.id);
                            const rect = stage.current.getBoundingClientRect();
                            setHoverPos({ x: e.clientX - rect.left, y: e.clientY - rect.top });
                        }, onMouseMove: (e) => {
                            if (!settled)
                                return;
                            const rect = stage.current.getBoundingClientRect();
                            setHoverPos({ x: e.clientX - rect.left, y: e.clientY - rect.top });
                        }, onClick: () => settled && setActive(active === s.id ? null : s.id) },
                        React.createElement("div", { className: "core" }),
                        React.createElement("span", { className: "star-label" }, s.name)));
                }),
                hover && settled && (React.createElement("div", { className: "star-tooltip", style: { left: hoverPos.x, top: hoverPos.y } }, (() => {
                    const s = CONFIG.stars.find(x => x.id === hover);
                    return (React.createElement(React.Fragment, null,
                        React.createElement("div", { className: "meta" }, s.domain),
                        React.createElement("div", { className: "name" }, s.name),
                        React.createElement("div", { className: "desc" }, s.desc)));
                })()))),
            active && (React.createElement("div", { className: "star-detail glass glass-strong " + (active ? "on" : "") },
                React.createElement("button", { className: "close", onClick: () => setActive(null), "aria-label": "Close" }, "\u00D7"),
                (() => {
                    const s = CONFIG.stars.find(x => x.id === active);
                    return (React.createElement("div", { className: "row" },
                        React.createElement("div", { className: "col-1" },
                            React.createElement("div", { className: "name" }, s.name),
                            React.createElement("div", { className: "domain" }, s.domain)),
                        React.createElement("div", { className: "col-2" },
                            React.createElement("div", { className: "desc" }, s.desc),
                            React.createElement("div", { style: {
                                    marginTop: 14, fontFamily: 'JetBrains Mono, monospace',
                                    fontSize: 10, letterSpacing: '.15em', color: 'var(--ink-mute)', textTransform: 'uppercase',
                                } }, "Cultural meaning \u00B7 review with advisors before publication"))));
                })())))));
}
// ─────────────────────────────────────────────────────────────
// EXPERIENCE · CULTURAL · FINAL
// ─────────────────────────────────────────────────────────────
function Experience() {
    return (React.createElement("section", { className: "experience container", id: "experience" },
        React.createElement("div", { className: "section-head reveal" },
            React.createElement("div", { className: "eyebrow" }, "SECTION 04 \u00B7 EXPERIENCE"),
            React.createElement("h2", null, "Three modes of presence."),
            React.createElement("p", null, "Each layer of the experience is designed to meet the user where they are \u2014 at the window, in the room, inside the story.")),
        React.createElement("div", { className: "exp-grid" }, CONFIG.experiences.map((e, i) => (React.createElement("div", { key: i, className: "exp-card glass reveal " + e.v },
            React.createElement("div", { className: "index" }, e.index),
            React.createElement("div", { className: "visual", "data-label": e.label },
                React.createElement("div", { className: "grid-overlay" })),
            React.createElement("h3", null, e.title),
            React.createElement("div", { className: "desc" }, e.desc),
            React.createElement("div", { className: "note" },
                React.createElement("span", { className: "pulse" }),
                React.createElement("span", null, e.note))))))));
}
function Cultural() {
    return (React.createElement("section", { className: "cultural container", id: "culture" },
        React.createElement("div", { className: "cult-grid" },
            React.createElement("div", { className: "left reveal" },
                React.createElement("div", { className: "eyebrow" }, "SECTION 05 \u00B7 KAUPAPA"),
                React.createElement("h2", null, "Held with care, not consumed."),
                React.createElement("p", null, "Matariki is not content. It is a relationship \u2014 between people, ancestors, the land, and the night sky. This project is a research prototype shaped by kaupapa M\u0101ori values, asking how spatial computing might serve cultural narrative without flattening it."),
                React.createElement("div", { className: "review-tag" },
                    React.createElement("span", { style: { width: 5, height: 5, borderRadius: '50%', background: 'var(--warm)' } }),
                    "Kaupapa \u00B7 reviewed with cultural advisors")),
            React.createElement("div", { className: "values-list reveal" }, CONFIG.values.map((v, i) => (React.createElement("div", { key: i, className: "value-row", tabIndex: "0" },
                React.createElement("div", { className: "key" },
                    React.createElement("span", { className: "key-word" }, v.key),
                    React.createElement("small", null, v.en),
                    React.createElement("span", { className: "hint", "aria-hidden": "true" }, "Hover \u2192")),
                React.createElement("div", { className: "desc-wrap" },
                    React.createElement("div", { className: "desc" }, v.desc)))))))));
}
function Final() {
    return (React.createElement("section", { className: "final container", id: "contact" },
        React.createElement("div", { className: "reveal" },
            React.createElement("div", { className: "eyebrow", style: { display: 'block', marginBottom: 28 } }, "SECTION 06 \u00B7 CREATOR"),
            React.createElement("h2", null,
                "Designed at the intersection of ",
                React.createElement("em", null, "culture"),
                ", ",
                React.createElement("em", null, "story"),
                ", and ",
                React.createElement("em", null, "spatial computing"),
                "."),
            React.createElement("div", { className: "ctas" },
                React.createElement("a", { className: "btn btn-primary", href: CONFIG.links.demo },
                    "Watch Demo ",
                    React.createElement("span", { className: "arrow" }, "\u2192")),
                React.createElement("a", { className: "btn", href: CONFIG.links.research },
                    "Read Research ",
                    React.createElement("span", { className: "arrow" }, "\u2192")),
                React.createElement("a", { className: "btn", href: CONFIG.links.portfolio },
                    "View Portfolio ",
                    React.createElement("span", { className: "arrow" }, "\u2192")),
                React.createElement("a", { className: "btn", href: CONFIG.links.contact },
                    "Contact ",
                    React.createElement("span", { className: "arrow" }, "\u2192"))),
            React.createElement("div", { className: "creator-card glass" },
                React.createElement("div", { className: "avatar" },
                    React.createElement("img", { src: "assets/creator-photo.jpg", alt: CONFIG.creator.name })),
                React.createElement("div", null,
                    React.createElement("div", { className: "role" }, CONFIG.creator.role),
                    React.createElement("div", { className: "name" }, CONFIG.creator.name),
                    React.createElement("div", { className: "bio" }, CONFIG.creator.bio)))),
        React.createElement("footer", { className: "container", style: { marginTop: 100 } },
            React.createElement("span", null, "\u00A9 2026 \u00B7 Guardians of Matariki"),
            React.createElement("div", { className: "links" },
                React.createElement("a", { href: "#demo" }, "Demo"),
                React.createElement("a", { href: "https://openrepository.aut.ac.nz/items/68b37076-8eab-45a1-bd65-c9f4f5721e3b", target: "_blank", rel: "noopener noreferrer" }, "Research"),
                React.createElement("a", { href: "mailto:peresethomas649@gmail.com" }, "Contact")))));
}
// ─────────────────────────────────────────────────────────────
// ROOT APP
// ─────────────────────────────────────────────────────────────
function App() {
    const [tweak, setTweak] = useTweaks(TWEAK_DEFAULTS);
    useReveal();
    useEffect(() => {
        const r = document.documentElement;
        r.style.setProperty('--accent', tweak.accent);
        r.style.setProperty('--blur', tweak.blur + 'px');
    }, [tweak.accent, tweak.blur]);
    return (React.createElement(React.Fragment, null,
        React.createElement(Hero, { tweak: tweak }),
        React.createElement(HeadsetSection, { tweak: tweak }),
        React.createElement(StarsSection, { tweak: tweak }),
        React.createElement(Experience, null),
        React.createElement(Cultural, null),
        React.createElement(Final, null)));
}
ReactDOM.createRoot(document.getElementById('app')).render(React.createElement(App, null));
